In [1]:
#!pip install matplotlib
import numpy as np
import pandas as pd
from warnings import warn
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel("q011.xlsx")

In [4]:
data.head()

,Код склада,Название склада,Дата,Код гр.,Название гр.,Код товара,1 наименование,2 наименование,кол-во,Сумма в пр.ценах,Сумма в ср. зак,Сумма в баз. Ценах,Стоимость одной штуки
0,E,Б Грузино хоз,2017-02-07,Q01,Бытовая химия,23141391,Щетка зубная Oral-B Advantage Artic,Щетка зубная Oral-B Advantage Artic,2,330.0,160.74,350.0,175.0
1,E,Б Грузино хоз,2017-02-07,Q01,Бытовая химия,23310100,Мыло Absolut 90г алоэ,Мыло Absolut 90г алоэ,1,33.0,21.53,35.0,35.0
2,E,Б Грузино хоз,2017-02-07,Q01,Бытовая химия,23310483,Паста зубная Семейная в тубе кора дуба,Паста зубная Семейная в тубе кора дуба мать-ма...,1,44.0,24.08,45.0,45.0
3,E,Б Грузино хоз,2017-02-07,Q01,Бытовая химия,23320536,Прокладки гигиенические Libresse Инвизиб,Прокладки гигиенические Libresse Инвизибл Норм...,1,129.0,80.64,129.0,129.0
4,E,Б Грузино хоз,2017-02-07,Q01,Бытовая химия,23320680,Порошок зубной Мятный,Порошок зубной Мятный,1,28.0,16.23,29.0,29.0

In [5]:
print('Кол-во уникальных товаров: ', data['Код товара'].unique().shape)
print('Объем данных: ', data.shape)

Кол-во уникальных товаров:  (1886,)
Объем данных:  (853384, 13)

In [6]:
codes = data['Код товара'].unique()

In [7]:
data_code_test = data.loc[data['Код товара'] == codes[37]][['Дата', '1 наименование', 'кол-во', 'Стоимость одной штуки']]
data_code_test

,Дата,1 наименование,кол-во,Стоимость одной штуки
38,2017-03-07,Краска для волос Хна бесцветная иранская,1,27.0
1213,2017-08-20,Краска для волос Хна бесцветная иранская,2,27.0
1456,2017-08-27,Краска для волос Хна бесцветная иранская,4,27.0
2640,2017-10-17,Краска для волос Хна бесцветная иранская,1,27.0
3142,2017-11-18,Краска для волос Хна бесцветная иранская,1,27.0
...,...,...,...,...
821764,2018-11-30,Краска для волос Хна бесцветная иранская,1,27.0
824402,2019-02-22,Краска для волос Хна бесцветная иранская,1,29.0
845580,2020-10-04,Краска для волос Хна бесцветная иранская,1,39.0
847992,2020-09-05,Краска для волос Хна бесцветная иранская,3,39.0
848871,2020-05-18,Краска для волос Хна бесцветная иранская,1,39.0

In [9]:
from fbprophet import Prophet
from datetime import datetime
import time

ModuleNotFoundError: No module named 'fbprophet'

In [17]:
dates=data_code_test[['Дата']].values.reshape(1,-1)[0]
print(dates)

['2017-03-07T00:00:00.000000000' '2017-08-20T00:00:00.000000000'
 '2017-08-27T00:00:00.000000000' '2017-10-17T00:00:00.000000000'
 '2017-11-18T00:00:00.000000000' '2018-07-01T00:00:00.000000000'
 '2018-03-28T00:00:00.000000000' '2018-04-26T00:00:00.000000000'
 '2018-05-05T00:00:00.000000000' '2018-12-05T00:00:00.000000000'
 '2018-07-21T00:00:00.000000000' '2018-04-08T00:00:00.000000000'
 '2018-08-25T00:00:00.000000000' '2018-09-18T00:00:00.000000000'
 '2019-12-04T00:00:00.000000000' '2019-05-27T00:00:00.000000000'
 '2019-08-24T00:00:00.000000000' '2019-12-19T00:00:00.000000000'
 '2020-04-01T00:00:00.000000000' '2020-03-03T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-03-05T00:00:00.000000000'
 '2020-05-24T00:00:00.000000000' '2020-05-27T00:00:00.000000000'
 '2020-05-28T00:00:00.000000000' '2020-05-30T00:00:00.000000000'
 '2020-04-06T00:00:00.000000000' '2020-11-06T00:00:00.000000000'
 '2017-12-07T00:00:00.000000000' '2017-07-15T00:00:00.000000000'
 '2017-07-25T00:00:00.000000000' '2017-07-27T00:00:00.000000000'
 '2017-08-20T00:00:00.000000000' '2017-10-22T00:00:00.000000000'
 '2017-11-25T00:00:00.000000000' '2018-01-03T00:00:00.000000000'
 '2018-04-15T00:00:00.000000000' '2018-10-31T00:00:00.000000000'
 '2018-11-15T00:00:00.000000000' '2019-01-19T00:00:00.000000000'
 '2019-02-17T00:00:00.000000000' '2019-03-16T00:00:00.000000000'
 '2019-04-30T00:00:00.000000000' '2019-05-14T00:00:00.000000000'
 '2019-10-18T00:00:00.000000000' '2020-02-27T00:00:00.000000000'
 '2020-04-16T00:00:00.000000000' '2020-04-24T00:00:00.000000000'
 '2020-06-06T00:00:00.000000000' '2020-06-13T00:00:00.000000000'
 '2017-10-09T00:00:00.000000000' '2017-09-24T00:00:00.000000000'
 '2017-10-29T00:00:00.000000000' '2017-07-12T00:00:00.000000000'
 '2017-10-12T00:00:00.000000000' '2017-12-24T00:00:00.000000000'
 '2018-03-25T00:00:00.000000000' '2018-11-04T00:00:00.000000000'
 '2018-07-17T00:00:00.000000000' '2018-07-29T00:00:00.000000000'
 '2018-08-15T00:00:00.000000000' '2018-10-29T00:00:00.000000000'
 '2018-01-11T00:00:00.000000000' '2018-11-16T00:00:00.000000000'
 '2018-11-26T00:00:00.000000000' '2019-09-01T00:00:00.000000000'
 '2019-01-18T00:00:00.000000000' '2019-10-02T00:00:00.000000000'
 '2019-02-16T00:00:00.000000000' '2019-05-21T00:00:00.000000000'
 '2019-02-06T00:00:00.000000000' '2019-07-19T00:00:00.000000000'
 '2019-11-17T00:00:00.000000000' '2020-01-16T00:00:00.000000000'
 '2017-08-28T00:00:00.000000000' '2017-09-17T00:00:00.000000000'
 '2017-05-12T00:00:00.000000000' '2018-04-01T00:00:00.000000000'
 '2018-03-02T00:00:00.000000000' '2018-03-24T00:00:00.000000000'
 '2018-12-04T00:00:00.000000000' '2018-04-18T00:00:00.000000000'
 '2018-07-14T00:00:00.000000000' '2018-09-29T00:00:00.000000000'
 '2019-01-20T00:00:00.000000000' '2019-11-09T00:00:00.000000000'
 '2019-09-13T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2017-07-16T00:00:00.000000000' '2017-01-10T00:00:00.000000000'
 '2018-01-13T00:00:00.000000000' '2018-07-23T00:00:00.000000000'
 '2019-10-02T00:00:00.000000000' '2019-07-04T00:00:00.000000000'
 '2019-05-27T00:00:00.000000000' '2020-02-23T00:00:00.000000000'
 '2020-03-21T00:00:00.000000000' '2020-04-24T00:00:00.000000000'
 '2020-05-29T00:00:00.000000000' '2018-02-07T00:00:00.000000000'
 '2019-04-03T00:00:00.000000000' '2019-04-29T00:00:00.000000000'
 '2019-06-13T00:00:00.000000000' '2019-07-22T00:00:00.000000000'
 '2019-10-08T00:00:00.000000000' '2019-11-10T00:00:00.000000000'
 '2019-12-10T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-05-16T00:00:00.000000000' '2020-11-06T00:00:00.000000000'
 '2017-08-26T00:00:00.000000000' '2018-04-07T00:00:00.000000000'
 '2018-10-19T00:00:00.000000000' '2018-01-12T00:00:00.000000000'
 '2017-07-29T00:00:00.000000000' '2017-01-08T00:00:00.000000000'
 '2017-09-10T00:00:00.000000000' '2018-01-16T00:00:00.000000000'
 '2018-05-03T00:00:00.000000000' '2018-10-04T00:00:00.000000000'
 '2018-04-18T00:00:00.000000000' '2018-05-20T00:00:00.000000000'
 '2018-06-21T00:00:00.000000000' '2018-05-08T00:00:00.000000000'
 '2018-08-29T00:00:00.000000000' '2018-09-17T00:00:00.000000000'
 '2018-10-10T00:00:00.000000000' '2019-10-02T00:00:00.000000000'
 '2019-04-14T00:00:00.000000000' '2019-09-14T00:00:00.000000000'
 '2020-01-03T00:00:00.000000000' '2020-03-04T00:00:00.000000000'
 '2020-09-06T00:00:00.000000000' '2017-09-16T00:00:00.000000000'
 '2017-01-10T00:00:00.000000000' '2017-10-30T00:00:00.000000000'
 '2017-05-11T00:00:00.000000000' '2017-11-19T00:00:00.000000000'
 '2018-01-15T00:00:00.000000000' '2018-06-10T00:00:00.000000000'
 '2018-11-15T00:00:00.000000000' '2019-03-15T00:00:00.000000000'
 '2019-05-31T00:00:00.000000000' '2019-04-06T00:00:00.000000000'
 '2019-07-16T00:00:00.000000000' '2019-09-29T00:00:00.000000000'
 '2020-06-13T00:00:00.000000000' '2017-07-20T00:00:00.000000000'
 '2017-12-08T00:00:00.000000000' '2017-08-11T00:00:00.000000000'
 '2017-11-28T00:00:00.000000000' '2017-12-19T00:00:00.000000000'
 '2018-02-28T00:00:00.000000000' '2018-10-03T00:00:00.000000000'
 '2019-01-13T00:00:00.000000000' '2019-01-25T00:00:00.000000000'
 '2019-12-02T00:00:00.000000000' '2019-04-18T00:00:00.000000000'
 '2019-07-13T00:00:00.000000000' '2019-07-19T00:00:00.000000000'
 '2019-08-11T00:00:00.000000000' '2020-04-24T00:00:00.000000000'
 '2019-08-03T00:00:00.000000000' '2018-03-31T00:00:00.000000000'
 '2018-08-10T00:00:00.000000000' '2019-03-14T00:00:00.000000000'
 '2019-03-16T00:00:00.000000000' '2019-06-28T00:00:00.000000000'
 '2017-07-26T00:00:00.000000000' '2017-08-22T00:00:00.000000000'
 '2017-12-23T00:00:00.000000000' '2018-08-04T00:00:00.000000000'
 '2018-08-20T00:00:00.000000000' '2018-09-22T00:00:00.000000000'
 '2018-12-11T00:00:00.000000000' '2018-11-18T00:00:00.000000000'
 '2019-04-13T00:00:00.000000000' '2019-10-05T00:00:00.000000000'
 '2018-01-16T00:00:00.000000000' '2018-10-06T00:00:00.000000000'
 '2018-07-21T00:00:00.000000000' '2018-12-08T00:00:00.000000000'
 '2018-08-19T00:00:00.000000000' '2018-09-22T00:00:00.000000000'
 '2019-04-25T00:00:00.000000000' '2020-05-30T00:00:00.000000000'
 '2017-12-11T00:00:00.000000000' '2019-10-24T00:00:00.000000000'
 '2020-06-05T00:00:00.000000000' '2017-08-19T00:00:00.000000000'
 '2017-08-22T00:00:00.000000000' '2017-12-17T00:00:00.000000000'
 '2017-12-22T00:00:00.000000000' '2018-01-28T00:00:00.000000000'
 '2018-02-16T00:00:00.000000000' '2018-03-18T00:00:00.000000000'
 '2018-06-05T00:00:00.000000000' '2018-06-17T00:00:00.000000000'
 '2018-07-30T00:00:00.000000000' '2018-03-11T00:00:00.000000000'
 '2018-12-22T00:00:00.000000000' '2019-04-05T00:00:00.000000000'
 '2019-11-05T00:00:00.000000000' '2019-08-08T00:00:00.000000000'
 '2019-01-12T00:00:00.000000000' '2020-05-20T00:00:00.000000000'
 '2017-05-07T00:00:00.000000000' '2018-12-02T00:00:00.000000000'
 '2018-04-03T00:00:00.000000000' '2017-10-28T00:00:00.000000000'
 '2018-03-02T00:00:00.000000000' '2018-04-16T00:00:00.000000000'
 '2018-05-05T00:00:00.000000000' '2018-06-17T00:00:00.000000000'
 '2018-10-07T00:00:00.000000000' '2018-11-11T00:00:00.000000000'
 '2019-01-29T00:00:00.000000000' '2019-02-03T00:00:00.000000000'
 '2019-04-30T00:00:00.000000000' '2019-10-05T00:00:00.000000000'
 '2019-12-06T00:00:00.000000000' '2019-06-23T00:00:00.000000000'
 '2019-12-07T00:00:00.000000000' '2019-08-13T00:00:00.000000000'
 '2019-08-18T00:00:00.000000000' '2019-09-21T00:00:00.000000000'
 '2020-03-17T00:00:00.000000000' '2017-07-25T00:00:00.000000000'
 '2018-07-12T00:00:00.000000000' '2018-12-16T00:00:00.000000000'
 '2019-06-01T00:00:00.000000000' '2020-07-03T00:00:00.000000000'
 '2017-12-30T00:00:00.000000000' '2018-03-13T00:00:00.000000000'
 '2018-04-16T00:00:00.000000000' '2018-05-28T00:00:00.000000000'
 '2018-07-26T00:00:00.000000000' '2018-10-29T00:00:00.000000000'
 '2018-11-16T00:00:00.000000000' '2019-08-25T00:00:00.000000000'
 '2017-07-29T00:00:00.000000000' '2017-09-13T00:00:00.000000000'
 '2017-10-13T00:00:00.000000000' '2018-03-20T00:00:00.000000000'
 '2018-03-30T00:00:00.000000000' '2018-05-15T00:00:00.000000000'
 '2018-05-26T00:00:00.000000000' '2018-06-24T00:00:00.000000000'
 '2018-06-07T00:00:00.000000000' '2018-11-07T00:00:00.000000000'
 '2018-10-25T00:00:00.000000000' '2019-07-01T00:00:00.000000000'
 '2019-03-13T00:00:00.000000000' '2019-05-27T00:00:00.000000000'
 '2019-06-06T00:00:00.000000000' '2019-07-07T00:00:00.000000000'
 '2019-12-07T00:00:00.000000000' '2019-06-08T00:00:00.000000000'
 '2019-08-19T00:00:00.000000000' '2019-09-14T00:00:00.000000000'
 '2019-09-21T00:00:00.000000000' '2019-10-14T00:00:00.000000000'
 '2019-05-12T00:00:00.000000000' '2020-11-03T00:00:00.000000000'
 '2020-03-14T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-06-25T00:00:00.000000000' '2017-07-09T00:00:00.000000000'
 '2017-09-16T00:00:00.000000000' '2018-01-30T00:00:00.000000000'
 '2017-11-07T00:00:00.000000000' '2018-01-26T00:00:00.000000000'
 '2018-10-26T00:00:00.000000000' '2018-04-11T00:00:00.000000000'
 '2018-12-30T00:00:00.000000000' '2019-02-01T00:00:00.000000000'
 '2019-08-01T00:00:00.000000000' '2019-08-26T00:00:00.000000000'
 '2020-01-19T00:00:00.000000000' '2017-07-07T00:00:00.000000000'
 '2017-11-20T00:00:00.000000000' '2018-06-21T00:00:00.000000000'
 '2018-06-08T00:00:00.000000000' '2018-11-28T00:00:00.000000000'
 '2018-07-12T00:00:00.000000000' '2019-07-02T00:00:00.000000000'
 '2019-02-18T00:00:00.000000000' '2019-04-18T00:00:00.000000000'
 '2020-11-06T00:00:00.000000000' '2020-06-13T00:00:00.000000000'
 '2017-12-08T00:00:00.000000000' '2017-12-16T00:00:00.000000000'
 '2017-12-30T00:00:00.000000000' '2018-01-03T00:00:00.000000000'
 '2018-12-03T00:00:00.000000000' '2018-11-05T00:00:00.000000000'
 '2018-04-08T00:00:00.000000000' '2018-08-24T00:00:00.000000000'
 '2019-04-01T00:00:00.000000000' '2019-01-14T00:00:00.000000000'
 '2019-02-22T00:00:00.000000000' '2020-04-27T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-05-25T00:00:00.000000000'
 '2020-10-06T00:00:00.000000000' '2020-02-07T00:00:00.000000000'
 '2017-02-08T00:00:00.000000000' '2017-06-08T00:00:00.000000000'
 '2017-12-24T00:00:00.000000000' '2018-03-01T00:00:00.000000000'
 '2018-08-01T00:00:00.000000000' '2018-02-03T00:00:00.000000000'
 '2019-05-26T00:00:00.000000000' '2019-10-29T00:00:00.000000000'
 '2019-11-16T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-03-27T00:00:00.000000000' '2020-10-05T00:00:00.000000000'
 '2020-03-06T00:00:00.000000000' '2017-12-07T00:00:00.000000000'
 '2017-07-22T00:00:00.000000000' '2017-11-26T00:00:00.000000000'
 '2018-07-01T00:00:00.000000000' '2018-05-19T00:00:00.000000000'
 '2018-01-09T00:00:00.000000000' '2018-09-16T00:00:00.000000000'
 '2018-11-27T00:00:00.000000000' '2019-01-13T00:00:00.000000000'
 '2019-08-05T00:00:00.000000000' '2019-08-31T00:00:00.000000000'
 '2019-05-09T00:00:00.000000000' '2019-11-09T00:00:00.000000000'
 '2019-12-09T00:00:00.000000000' '2019-09-10T00:00:00.000000000'
 '2019-10-15T00:00:00.000000000' '2019-11-14T00:00:00.000000000'
 '2019-11-16T00:00:00.000000000' '2020-04-16T00:00:00.000000000'
 '2020-04-19T00:00:00.000000000' '2020-01-05T00:00:00.000000000'
 '2020-05-30T00:00:00.000000000' '2020-06-27T00:00:00.000000000'
 '2018-08-02T00:00:00.000000000' '2018-02-16T00:00:00.000000000'
 '2018-02-22T00:00:00.000000000' '2018-04-16T00:00:00.000000000'
 '2018-02-06T00:00:00.000000000' '2018-09-23T00:00:00.000000000'
 '2018-11-11T00:00:00.000000000' '2019-01-13T00:00:00.000000000'
 '2019-10-17T00:00:00.000000000' '2020-07-05T00:00:00.000000000'
 '2020-06-25T00:00:00.000000000' '2017-12-08T00:00:00.000000000'
 '2018-06-25T00:00:00.000000000' '2018-11-07T00:00:00.000000000'
 '2018-08-14T00:00:00.000000000' '2018-08-30T00:00:00.000000000'
 '2018-10-30T00:00:00.000000000' '2018-11-15T00:00:00.000000000'
 '2019-03-02T00:00:00.000000000' '2019-04-16T00:00:00.000000000'
 '2019-05-18T00:00:00.000000000' '2019-10-06T00:00:00.000000000'
 '2019-07-23T00:00:00.000000000' '2019-02-08T00:00:00.000000000'
 '2019-08-20T00:00:00.000000000' '2019-08-28T00:00:00.000000000'
 '2019-09-13T00:00:00.000000000' '2020-02-15T00:00:00.000000000'
 '2020-09-04T00:00:00.000000000' '2020-05-26T00:00:00.000000000'
 '2017-07-18T00:00:00.000000000' '2017-07-19T00:00:00.000000000'
 '2017-10-12T00:00:00.000000000' '2018-03-28T00:00:00.000000000'
 '2018-06-17T00:00:00.000000000' '2018-06-25T00:00:00.000000000'
 '2018-10-30T00:00:00.000000000' '2018-03-11T00:00:00.000000000'
 '2018-09-11T00:00:00.000000000' '2018-11-30T00:00:00.000000000'
 '2019-02-22T00:00:00.000000000' '2020-10-04T00:00:00.000000000'
 '2020-09-05T00:00:00.000000000' '2020-05-18T00:00:00.000000000']

In [22]:
ds = pd.to_datetime(dates)

In [24]:
ds.shape

(386,)

In [26]:
ds

DatetimeIndex(['2017-03-07', '2017-08-20', '2017-08-27', '2017-10-17',
               '2017-11-18', '2018-07-01', '2018-03-28', '2018-04-26',
               '2018-05-05', '2018-12-05',
               ...
               '2018-06-17', '2018-06-25', '2018-10-30', '2018-03-11',
               '2018-09-11', '2018-11-30', '2019-02-22', '2020-10-04',
               '2020-09-05', '2020-05-18'],
              dtype='datetime64[ns]', length=386, freq=None)